[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "avalanche.fuji"
provider = "http://127.0.0.1:8533"
provider_poa = true
symbol = "AVAX"
evm_finalization_secs = 2
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 5
