[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
gas = 8_000_000
name = "boba.rinkeby"
provider = "http://127.0.0.1:8539"
provider_poa = true
symbol = "oETH"
evm_waiting_timeout_secs = 60
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 10
