[contracts]
# ERC2362PriceFeed contracts
pricefeeds = [
  "0xa6ADEB16Cc5aB0d6A79957D9cf6234F508c33A74", # BtcUsdPriceFeed 
  "0x542e8aD2e1AA508CC254E536DA98291776A15c65"  # EthUsdPriceFeed
]

[account]
# The address of the EOA that will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
min_secs_between_request_updates = 300

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8539"
provider_timeout_secs = 120
gas_price = 15000000
gas = 8000000
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 2
