[network]
from = "0x01c72381A423636E7eC80E3784983CDC29a3c7E9"
gas = 8_000_000
name = "celo.alfajores"
provider = "http://127.0.0.1:8538"
provider_poa = true
symbol = "CELO"
evm_finalization_secs = 30
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 5
