[pricefeeds]
# ERC2362PriceFeed contracts
addresses = [
  "0x4F8Ac2D45475A1894Cb85E3A21173d5e83041083", # BtcUsdPriceFeed 
  "0xD182e334e3c7140F8a520d326E333CA5f1FB7dDa"  # OmgUsdtPriceFeed
]
thresholds = [
  2.0, # BtcUsdPriceFeed
  2.0  # OmgUsdtPriceFeed
]

[account]
# The address of the EOA that will create the transactions
# (needs to have a high enough balance)
address = "0xA0E824822C6A5C28DE3568Df99604d68E9FD9C8c"
min_secs_between_request_updates = 300
max_secs_between_request_updates = 3600

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8538"
provider_timeout_secs = 120
gas_price = 500000000
gas = 8000000
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 2
