[network]
from = "0x10E824822C6A5C28dE3568DF99604D68e9fd9c8c"
gas = 200_000
gas_price = 1
name = "conflux.testnet"
provider = "http://127.0.0.1:8540"
provider_timeout_secs = 120
symbol = "CFX"
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 2
witnet_resolution_secs = 240
witnet_toolkit_timeout_secs = 15
