[contracts]
# ERC2362PriceFeed contracts
pricefeeds = [
  "0x43Fe8778389f4EB98e82B750DCCAfF0D7d57778c", # BtcUsdPriceFeed 
  "0x031699240f710B47e92Df7766C06ee6C22A75df1"  # EthUsdPriceFeed
]

[account]
# The address of the EOA that will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
min_secs_between_request_updates = 3600

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8545"
provider_timeout_secs = 120
gas_price = 10000000000
gas = 250000
tx_waiting_timeout_secs = 200
tx_polling_latency_secs = 20
