[contracts]
# ERC2362PriceFeed contracts
pricefeeds = [
  "", # BtcUsdPriceFeed 
  ""  # EthUsdPriceFeed
]


[account]
# The address of the EOA that will create the transactions
# (needs to have a high enough balance)
address = ""
# 24 hours
min_secs_between_request_updates = 86400

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:9545"
provider_timeout_secs = 120
gas_price = "estimate_medium"
gas = 250000
tx_waiting_timeout_secs = 900
tx_polling_latency_secs = 30
