[network]
from = "0x102cB4Da51a9936ba2297be8C930B4Ca658586DA"
name = "ethereum.mainnet"
gas = 350_000
provider = "http://127.0.0.1:9545"
symbol = "ETH"
evm_finalization_secs = 120
evm_waiting_timeout_secs = 900
evm_polling_latency_secs = 30
