[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "ethereum.goerli"
gas = 350_000
provider = "http://127.0.0.1:8545"
provider_poa = true
symbol = "gETH"
tx_waiting_timeout_secs = 200
tx_polling_latency_secs = 20
