[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "ethereum.rinkeby"
gas = 350_000
provider = "http://127.0.0.1:8544"
provider_poa = true
symbol = "rETH"
evm_finalization_secs = 90
evm_waiting_timeout_secs = 200
evm_polling_latency_secs = 20

