[contract]
# The contracts the poller needs to interact with
wrb = ""

# Addresses of BtcUsdPriceFeed, EthUsdPriceFeed and GoldEurPriceFeed contracts
pricefeeds = [
  "",
  ""
]

[account]
# The ethereum address which will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
min_secs_between_request_updates = 3600

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:9545"
provider_timeout_secs = 120
gas_price = 10000000000
gas = 4000000
tx_waiting_timeout_secs = 200
tx_polling_latency_secs = 20
