[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "kcc.testnet"
provider = "http://127.0.0.1:8537"
provider_poa = true
symbol = "KCS"
evm_finalization_secs = 30
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 6
