[contract]
# The contracts the poller needs to interact with
wrb = "0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d"

# Addresses of BtcUsdPriceFeed, EthUsdPriceFeed and GoldEurPriceFeed contracts
pricefeeds = [
  "0x9b3C5A6cB55E027d9ae6f265f6FB6fFA86e7b35E",
  "0xA996939e6a07a0D1D6376c59BE515d8441f5E9b8"
]

[account]
# The ethereum address which will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
min_secs_between_request_updates = 3600

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8542"
provider_timeout_secs = 120
gas_price = 10000000000
gas = 250000
tx_waiting_timeout_secs = 200
tx_polling_latency_secs = 20
