[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
gas = 30_000_000
gas_price = 15_000_000_000
name = "metis.rinkeby"
provider = "http://127.0.0.1:8536"
provider_timeout_secs = 60
symbol = "tMETIS"
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 6
witnet_resolution_secs = 240
witnet_toolkit_timeout_secs = 15
