[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "metis.rinkeby"
provider = "http://localhost:8536"
provider_poa = true
symbol = "tMETIS"
evm_finalization_secs = 48
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 6
