[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "metis.rinkeby"
provider = "http://localhost:8536"
provider_poa = true
symbol = "tMETIS"
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 6

