[contract]
# The WRB entry point which the poller needs to interact with
wrb = "0x9AEC8fDABa5AC2add0C6be7d833D05ed35240A3c"

# Addresses of BtcUsdPriceFeed and EthUsdPriceFeed contracts
pricefeeds = [
  "0xFc2d03FC7983690e59b19742Df95921f6f427619",
  "0xc892156C21Fc754B1786872313e2dd34DbA779DF"
]

[account]
# The address of the EOA that will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
min_secs_between_request_updates = 300

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8539"
provider_timeout_secs = 120
gas_price = 15000000
gas = 8000000
tx_waiting_timeout_secs = 60
tx_polling_latency_secs = 2
