[network]
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
name = "polygon.mumbai"
#gas = 300_000
#gas_price = 30_000_000_000
provider = "http://127.0.0.1:8535"
provider_poa = true
symbol = "MATIC"
evm_finalization_secs = 20
evm_waiting_timeout_secs = 120
evm_polling_latency_secs = 2
