[contract]
# The contracts the poller needs to interact with
wrb = "0xb55Ab5eDeb7256242Ae4C632e75bcbd4E6cc1fbB"
# Addresses of BtcUsdPriceFeed, EthUsdPriceFeed and GoldEurPriceFeed contracts
pricefeeds = ["0x49C0BCce51a8B28f92d008394F06d5B259657F33",
              "0x75fC826f7660f4e79823aA02337C77c975cBFa50",
              "0x6D7AC08d92f2428ce05B3725B4087810f625d059"]

[account]
# The ethereum address which will create the transactions
# (needs to have a high enough balance)
address = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"

[network]
# The provider to which the poller needs to connect
provider = "http://127.0.0.1:8544"
provider_timeout_secs = 120
gas_price = 10000000000
gas = 4000000
tx_waiting_timeout_secs = 150
tx_polling_latency_secs = 15
